// <auto-generated />
// このファイルは Resources.tt により自動生成されています。手動で編集しないでください。
// Source: ../resources.json

namespace Sony.Jin.Gateway.Properties
{
    /// <summary>
    /// resources.json から自動生成された文字列リソース。
    /// 値は実行時に JsonResourceManager 経由で取得されます。
    /// </summary>
    public static class Resources
    {
        /// <summary>
        /// Host Application
        /// </summary>
        public static string MainWindow_Title => JsonResourceManager.Instance["MainWindow_Title"];

        /// <summary>
        /// View(_V)
        /// </summary>
        public static string MainWindow_MenuView => JsonResourceManager.Instance["MainWindow_MenuView"];

        /// <summary>
        /// Live Current Data(_C)...
        /// </summary>
        public static string MainWindow_MenuLiveCurrent => JsonResourceManager.Instance["MainWindow_MenuLiveCurrent"];

        /// <summary>
        /// Snap Current Data(_R)...
        /// </summary>
        public static string MainWindow_MenuSnapCurrent => JsonResourceManager.Instance["MainWindow_MenuSnapCurrent"];

        /// <summary>
        /// Live Hardware Data(_H)...
        /// </summary>
        public static string MainWindow_MenuLiveHardware => JsonResourceManager.Instance["MainWindow_MenuLiveHardware"];

        /// <summary>
        /// Snap Hardware Data(_D)...
        /// </summary>
        public static string MainWindow_MenuSnapHardware => JsonResourceManager.Instance["MainWindow_MenuSnapHardware"];

        /// <summary>
        /// Tools(_T)
        /// </summary>
        public static string MainWindow_MenuTools => JsonResourceManager.Instance["MainWindow_MenuTools"];

        /// <summary>
        /// Loopback Client(_L)...
        /// </summary>
        public static string MainWindow_MenuLoopbackClient => JsonResourceManager.Instance["MainWindow_MenuLoopbackClient"];

        /// <summary>
        /// Stub Host Port(_S)...
        /// </summary>
        public static string MainWindow_MenuStubHostPort => JsonResourceManager.Instance["MainWindow_MenuStubHostPort"];

        /// <summary>
        /// Options(_O)...
        /// </summary>
        public static string MainWindow_MenuOptions => JsonResourceManager.Instance["MainWindow_MenuOptions"];

        /// <summary>
        /// Open Data Storage in File Explorer(_X)
        /// </summary>
        public static string MainWindow_MenuOpenRecordDirectory => JsonResourceManager.Instance["MainWindow_MenuOpenRecordDirectory"];

        /// <summary>
        /// Host Port
        /// </summary>
        public static string MainWindow_LabelHostPort => JsonResourceManager.Instance["MainWindow_LabelHostPort"];

        /// <summary>
        /// Debug Port
        /// </summary>
        public static string MainWindow_LabelDebugPort => JsonResourceManager.Instance["MainWindow_LabelDebugPort"];

        /// <summary>
        /// Log Port
        /// </summary>
        public static string MainWindow_LabelLogPort => JsonResourceManager.Instance["MainWindow_LabelLogPort"];

        /// <summary>
        /// Control History
        /// </summary>
        public static string MainWindow_LabelControlHistory => JsonResourceManager.Instance["MainWindow_LabelControlHistory"];

        /// <summary>
        /// Debug Port Transmit History
        /// </summary>
        public static string MainWindow_LabelDebugPortTransmitHistory => JsonResourceManager.Instance["MainWindow_LabelDebugPortTransmitHistory"];

        /// <summary>
        /// Debug Port Receive History
        /// </summary>
        public static string MainWindow_LabelDebugPortReceiveHistory => JsonResourceManager.Instance["MainWindow_LabelDebugPortReceiveHistory"];

        /// <summary>
        /// Log Port Receive History
        /// </summary>
        public static string MainWindow_LabelLogPortReceiveHistory => JsonResourceManager.Instance["MainWindow_LabelLogPortReceiveHistory"];

        /// <summary>
        /// Application Log History
        /// </summary>
        public static string MainWindow_LabelAppLogHistory => JsonResourceManager.Instance["MainWindow_LabelAppLogHistory"];

        /// <summary>
        /// Nop Count
        /// </summary>
        public static string MainWindow_LabelNopCount => JsonResourceManager.Instance["MainWindow_LabelNopCount"];

        /// <summary>
        /// PUB Socket
        /// </summary>
        public static string MainWindow_LabelPubSocket => JsonResourceManager.Instance["MainWindow_LabelPubSocket"];

        /// <summary>
        /// PULL Socket
        /// </summary>
        public static string MainWindow_LabelPullSocket => JsonResourceManager.Instance["MainWindow_LabelPullSocket"];

        /// <summary>
        /// Time
        /// </summary>
        public static string MainWindow_ColumnTime => JsonResourceManager.Instance["MainWindow_ColumnTime"];

        /// <summary>
        /// Type
        /// </summary>
        public static string MainWindow_ColumnType => JsonResourceManager.Instance["MainWindow_ColumnType"];

        /// <summary>
        /// Level
        /// </summary>
        public static string MainWindow_ColumnLevel => JsonResourceManager.Instance["MainWindow_ColumnLevel"];

        /// <summary>
        /// Message
        /// </summary>
        public static string MainWindow_ColumnMessage => JsonResourceManager.Instance["MainWindow_ColumnMessage"];

        /// <summary>
        /// Loopback Client
        /// </summary>
        public static string LoopbackWindow_Title => JsonResourceManager.Instance["LoopbackWindow_Title"];

        /// <summary>
        /// Receive Port Frame
        /// </summary>
        public static string LoopbackWindow_LabelReceivePortFrame => JsonResourceManager.Instance["LoopbackWindow_LabelReceivePortFrame"];

        /// <summary>
        /// Host: Serial Number
        /// </summary>
        public static string LoopbackWindow_LabelHostSerialNumber => JsonResourceManager.Instance["LoopbackWindow_LabelHostSerialNumber"];

        /// <summary>
        /// Host: Data Type
        /// </summary>
        public static string LoopbackWindow_LabelHostDataType => JsonResourceManager.Instance["LoopbackWindow_LabelHostDataType"];

        /// <summary>
        /// Host: Frame Length
        /// </summary>
        public static string LoopbackWindow_LabelHostFrameLength => JsonResourceManager.Instance["LoopbackWindow_LabelHostFrameLength"];

        /// <summary>
        /// Host: Receive Count
        /// </summary>
        public static string LoopbackWindow_LabelHostReceiveCount => JsonResourceManager.Instance["LoopbackWindow_LabelHostReceiveCount"];

        /// <summary>
        /// Debug: Response
        /// </summary>
        public static string LoopbackWindow_LabelDebugResponse => JsonResourceManager.Instance["LoopbackWindow_LabelDebugResponse"];

        /// <summary>
        /// Log: Message
        /// </summary>
        public static string LoopbackWindow_LabelLogMessage => JsonResourceManager.Instance["LoopbackWindow_LabelLogMessage"];

        /// <summary>
        /// Transmit Control Message
        /// </summary>
        public static string LoopbackWindow_LabelTransmitControlMessage => JsonResourceManager.Instance["LoopbackWindow_LabelTransmitControlMessage"];

        /// <summary>
        /// NOP
        /// </summary>
        public static string LoopbackWindow_LabelNop => JsonResourceManager.Instance["LoopbackWindow_LabelNop"];

        /// <summary>
        /// SNAP Current Graph
        /// </summary>
        public static string LoopbackWindow_LabelSnapCurrentGraph => JsonResourceManager.Instance["LoopbackWindow_LabelSnapCurrentGraph"];

        /// <summary>
        /// SNAP Hardware Graph
        /// </summary>
        public static string LoopbackWindow_LabelSnapHardwareGraph => JsonResourceManager.Instance["LoopbackWindow_LabelSnapHardwareGraph"];

        /// <summary>
        /// PRINT Message
        /// </summary>
        public static string LoopbackWindow_LabelPrintMessage => JsonResourceManager.Instance["LoopbackWindow_LabelPrintMessage"];

        /// <summary>
        /// DEBUG Command
        /// </summary>
        public static string LoopbackWindow_LabelDebugCommand => JsonResourceManager.Instance["LoopbackWindow_LabelDebugCommand"];

        /// <summary>
        /// SUB (Host)
        /// </summary>
        public static string LoopbackWindow_LabelSubHostSocket => JsonResourceManager.Instance["LoopbackWindow_LabelSubHostSocket"];

        /// <summary>
        /// SUB (Debug)
        /// </summary>
        public static string LoopbackWindow_LabelSubDebugSocket => JsonResourceManager.Instance["LoopbackWindow_LabelSubDebugSocket"];

        /// <summary>
        /// SUB (Log)
        /// </summary>
        public static string LoopbackWindow_LabelSubLogSocket => JsonResourceManager.Instance["LoopbackWindow_LabelSubLogSocket"];

        /// <summary>
        /// PUSH
        /// </summary>
        public static string LoopbackWindow_LabelPushSocket => JsonResourceManager.Instance["LoopbackWindow_LabelPushSocket"];

        /// <summary>
        /// Start
        /// </summary>
        public static string LoopbackWindow_ButtonStart => JsonResourceManager.Instance["LoopbackWindow_ButtonStart"];

        /// <summary>
        /// Stop
        /// </summary>
        public static string LoopbackWindow_ButtonStop => JsonResourceManager.Instance["LoopbackWindow_ButtonStop"];

        /// <summary>
        /// Transmit
        /// </summary>
        public static string LoopbackWindow_ButtonTransmit => JsonResourceManager.Instance["LoopbackWindow_ButtonTransmit"];

        /// <summary>
        /// Stub Port
        /// </summary>
        public static string StubWindow_Title => JsonResourceManager.Instance["StubWindow_Title"];

        /// <summary>
        /// Receive Host Port Frame
        /// </summary>
        public static string StubWindow_LabelReceiveHostPortFrame => JsonResourceManager.Instance["StubWindow_LabelReceiveHostPortFrame"];

        /// <summary>
        /// Full Data Folder
        /// </summary>
        public static string StubWindow_LabelFullDataLogDirectory => JsonResourceManager.Instance["StubWindow_LabelFullDataLogDirectory"];

        /// <summary>
        /// Hardware Data File
        /// </summary>
        public static string StubWindow_LabelHardwareDataLogFile => JsonResourceManager.Instance["StubWindow_LabelHardwareDataLogFile"];

        /// <summary>
        /// Data Type
        /// </summary>
        public static string StubWindow_LabelDataType => JsonResourceManager.Instance["StubWindow_LabelDataType"];

        /// <summary>
        /// Frame Size
        /// </summary>
        public static string StubWindow_LabelFrameSize => JsonResourceManager.Instance["StubWindow_LabelFrameSize"];

        /// <summary>
        /// Frame Interval
        /// </summary>
        public static string StubWindow_LabelFrameInterval => JsonResourceManager.Instance["StubWindow_LabelFrameInterval"];

        /// <summary>
        /// Serial Number
        /// </summary>
        public static string StubWindow_LabelSerialNumber => JsonResourceManager.Instance["StubWindow_LabelSerialNumber"];

        /// <summary>
        /// Receive Count
        /// </summary>
        public static string StubWindow_LabelReceiveCount => JsonResourceManager.Instance["StubWindow_LabelReceiveCount"];

        /// <summary>
        /// Receive Debug Port Frame
        /// </summary>
        public static string StubWindow_LabelReceiveDebugPortFrame => JsonResourceManager.Instance["StubWindow_LabelReceiveDebugPortFrame"];

        /// <summary>
        /// Insert Response
        /// </summary>
        public static string StubWindow_LabelInsertResponse => JsonResourceManager.Instance["StubWindow_LabelInsertResponse"];

        /// <summary>
        /// Error Command
        /// </summary>
        public static string StubWindow_LabelErrorCommand => JsonResourceManager.Instance["StubWindow_LabelErrorCommand"];

        /// <summary>
        /// Result Code
        /// </summary>
        public static string StubWindow_LabelResultCode => JsonResourceManager.Instance["StubWindow_LabelResultCode"];

        /// <summary>
        /// MCBJ/ASZ
        /// </summary>
        public static string StubWindow_LabelMcbjAsz => JsonResourceManager.Instance["StubWindow_LabelMcbjAsz"];

        /// <summary>
        /// dd_ep bias
        /// </summary>
        public static string StubWindow_LabelDdEpBias => JsonResourceManager.Instance["StubWindow_LabelDdEpBias"];

        /// <summary>
        /// dd_ep ep
        /// </summary>
        public static string StubWindow_LabelDdEpEp => JsonResourceManager.Instance["StubWindow_LabelDdEpEp"];

        /// <summary>
        /// mw_ac go0
        /// </summary>
        public static string StubWindow_LabelMwAcGo0 => JsonResourceManager.Instance["StubWindow_LabelMwAcGo0"];

        /// <summary>
        /// sv_info_sender start
        /// </summary>
        public static string StubWindow_LabelSvInfoSenderStart => JsonResourceManager.Instance["StubWindow_LabelSvInfoSenderStart"];

        /// <summary>
        /// sv_info_sender stop
        /// </summary>
        public static string StubWindow_LabelSvInfoSenderStop => JsonResourceManager.Instance["StubWindow_LabelSvInfoSenderStop"];

        /// <summary>
        /// mcbj set
        /// </summary>
        public static string StubWindow_LabelMcbjSet => JsonResourceManager.Instance["StubWindow_LabelMcbjSet"];

        /// <summary>
        /// asz set
        /// </summary>
        public static string StubWindow_LabelAszSet => JsonResourceManager.Instance["StubWindow_LabelAszSet"];

        /// <summary>
        /// Execution Time
        /// </summary>
        public static string StubWindow_LabelMcbjExecutionTime => JsonResourceManager.Instance["StubWindow_LabelMcbjExecutionTime"];

        /// <summary>
        /// Running
        /// </summary>
        public static string StubWindow_LabelMcbjRunning => JsonResourceManager.Instance["StubWindow_LabelMcbjRunning"];

        /// <summary>
        /// Raise Error
        /// </summary>
        public static string StubWindow_LabelMcbjRaiseError => JsonResourceManager.Instance["StubWindow_LabelMcbjRaiseError"];

        /// <summary>
        /// Receive Log Port Frame
        /// </summary>
        public static string StubWindow_LabelReceiveLogPortFrame => JsonResourceManager.Instance["StubWindow_LabelReceiveLogPortFrame"];

        /// <summary>
        /// Insert Message
        /// </summary>
        public static string StubWindow_LabelInsertMessage => JsonResourceManager.Instance["StubWindow_LabelInsertMessage"];

        /// <summary>
        /// Start
        /// </summary>
        public static string StubWindow_ButtonStart => JsonResourceManager.Instance["StubWindow_ButtonStart"];

        /// <summary>
        /// Stop
        /// </summary>
        public static string StubWindow_ButtonStop => JsonResourceManager.Instance["StubWindow_ButtonStop"];

        /// <summary>
        /// H/W Data only
        /// </summary>
        public static string StubWindow_ItemBeaconNoCurrent => JsonResourceManager.Instance["StubWindow_ItemBeaconNoCurrent"];

        /// <summary>
        /// H/W Data + Current/Low/10k
        /// </summary>
        public static string StubWindow_ItemBeaconCurrentLow10k => JsonResourceManager.Instance["StubWindow_ItemBeaconCurrentLow10k"];

        /// <summary>
        /// H/W Data + Current/High/10k
        /// </summary>
        public static string StubWindow_ItemBeaconCurrentHigh10k => JsonResourceManager.Instance["StubWindow_ItemBeaconCurrentHigh10k"];

        /// <summary>
        /// H/W Data + Current/High/50k
        /// </summary>
        public static string StubWindow_ItemBeaconCurrentHigh50k => JsonResourceManager.Instance["StubWindow_ItemBeaconCurrentHigh50k"];

        /// <summary>
        /// H/W Data + Current/High/100k
        /// </summary>
        public static string StubWindow_ItemBeaconCurrentHigh100k => JsonResourceManager.Instance["StubWindow_ItemBeaconCurrentHigh100k"];

        /// <summary>
        /// Diagnostics
        /// </summary>
        public static string StubWindow_ItemDiag => JsonResourceManager.Instance["StubWindow_ItemDiag"];

        /// <summary>
        /// Host Port Hardware Log (*.csv)|*.csv
        /// </summary>
        public static string StubWindow_FileDialogFilterHardwareLog => JsonResourceManager.Instance["StubWindow_FileDialogFilterHardwareLog"];

        /// <summary>
        /// Live Current Data
        /// </summary>
        public static string GraphWindow_TitleLiveCurrent => JsonResourceManager.Instance["GraphWindow_TitleLiveCurrent"];

        /// <summary>
        /// Live Hardware Data
        /// </summary>
        public static string GraphWindow_TitleLiveHardware => JsonResourceManager.Instance["GraphWindow_TitleLiveHardware"];

        /// <summary>
        /// Snap Current Data
        /// </summary>
        public static string GraphWindow_TitleSnapCurrent => JsonResourceManager.Instance["GraphWindow_TitleSnapCurrent"];

        /// <summary>
        /// Snap Hardware Data
        /// </summary>
        public static string GraphWindow_TitleSanpHardware => JsonResourceManager.Instance["GraphWindow_TitleSanpHardware"];

        /// <summary>
        /// Data
        /// </summary>
        public static string GraphWindow_LabelData => JsonResourceManager.Instance["GraphWindow_LabelData"];

        /// <summary>
        /// Median
        /// </summary>
        public static string GraphWindow_LabelMedian => JsonResourceManager.Instance["GraphWindow_LabelMedian"];

        /// <summary>
        /// RMS
        /// </summary>
        public static string GraphWindow_LabelRMS => JsonResourceManager.Instance["GraphWindow_LabelRMS"];

        /// <summary>
        /// Data Type
        /// </summary>
        public static string GraphWindow_LabelDataType => JsonResourceManager.Instance["GraphWindow_LabelDataType"];

        /// <summary>
        /// No Current
        /// </summary>
        public static string GraphWindow_LabelDataTypeNoCurrent => JsonResourceManager.Instance["GraphWindow_LabelDataTypeNoCurrent"];

        /// <summary>
        /// Low/10 kHz
        /// </summary>
        public static string GraphWindow_LabelDataTypeLow10k => JsonResourceManager.Instance["GraphWindow_LabelDataTypeLow10k"];

        /// <summary>
        /// High/10 kHz
        /// </summary>
        public static string GraphWindow_LabelDataTypeHigh10k => JsonResourceManager.Instance["GraphWindow_LabelDataTypeHigh10k"];

        /// <summary>
        /// High/50 kHz
        /// </summary>
        public static string GraphWindow_LabelDataTypeHigh50k => JsonResourceManager.Instance["GraphWindow_LabelDataTypeHigh50k"];

        /// <summary>
        /// High/100 kHz
        /// </summary>
        public static string GraphWindow_LabelDataTypeHigh100k => JsonResourceManager.Instance["GraphWindow_LabelDataTypeHigh100k"];

        /// <summary>
        /// Current (Low)
        /// </summary>
        public static string GraphWindow_LabelCurrentLow => JsonResourceManager.Instance["GraphWindow_LabelCurrentLow"];

        /// <summary>
        /// Current (High)
        /// </summary>
        public static string GraphWindow_LabelCurrentHigh => JsonResourceManager.Instance["GraphWindow_LabelCurrentHigh"];

        /// <summary>
        /// Current
        /// </summary>
        public static string GraphWindow_LabelCurrent => JsonResourceManager.Instance["GraphWindow_LabelCurrent"];

        /// <summary>
        /// Motor
        /// </summary>
        public static string GraphWindow_LabelMotor => JsonResourceManager.Instance["GraphWindow_LabelMotor"];

        /// <summary>
        /// (.1um)
        /// </summary>
        public static string GraphWindow_LabelMotorUnit => JsonResourceManager.Instance["GraphWindow_LabelMotorUnit"];

        /// <summary>
        /// Piezo
        /// </summary>
        public static string GraphWindow_LabelPiezo => JsonResourceManager.Instance["GraphWindow_LabelPiezo"];

        /// <summary>
        /// (nm)
        /// </summary>
        public static string GraphWindow_LabelPiezoUnit => JsonResourceManager.Instance["GraphWindow_LabelPiezoUnit"];

        /// <summary>
        /// Time
        /// </summary>
        public static string GraphWindow_LabelTime => JsonResourceManager.Instance["GraphWindow_LabelTime"];

        /// <summary>
        /// Snap
        /// </summary>
        public static string GraphWindow_ButtonSnap => JsonResourceManager.Instance["GraphWindow_ButtonSnap"];

        /// <summary>
        /// Save a screenshot of the current window as an image file.
        /// </summary>
        public static string GraphWindow_ToolTipCapture => JsonResourceManager.Instance["GraphWindow_ToolTipCapture"];

        /// <summary>
        /// Remove the graph currently displayed in this window.
        /// </summary>
        public static string GraphWindow_ToolTipDelete => JsonResourceManager.Instance["GraphWindow_ToolTipDelete"];

        /// <summary>
        /// Open a new window showing a frozen snapshot of the current graph and its underlying data.
        /// </summary>
        public static string GraphWindow_ToolTipSnap => JsonResourceManager.Instance["GraphWindow_ToolTipSnap"];

        /// <summary>
        /// PNG Image (*.png)|*.png|JPEG Image (*.jpg)|*.jpg|BMP Image (*.bmp)|*.bmp
        /// </summary>
        public static string GraphWindow_FileDialogFilterCapture => JsonResourceManager.Instance["GraphWindow_FileDialogFilterCapture"];

        /// <summary>
        /// Options
        /// </summary>
        public static string OptionsWindow_Title => JsonResourceManager.Instance["OptionsWindow_Title"];

        /// <summary>
        /// Data Storage Location
        /// </summary>
        public static string OptionsWindow_LabelRecordDirectoryGroup => JsonResourceManager.Instance["OptionsWindow_LabelRecordDirectoryGroup"];

        /// <summary>
        /// Base folder:
        /// </summary>
        public static string OptionsWindow_LabelRecordDirectoryBase => JsonResourceManager.Instance["OptionsWindow_LabelRecordDirectoryBase"];

        /// <summary>
        /// Automatically create a subfolder on startup
        /// </summary>
        public static string OptionsWindow_LabelRecordDirectoryAuto => JsonResourceManager.Instance["OptionsWindow_LabelRecordDirectoryAuto"];

        /// <summary>
        /// A uniquely named subfolder is created each time the application starts.
        /// </summary>
        public static string OptionsWindow_LabelRecordDirectoryAutoExplanation => JsonResourceManager.Instance["OptionsWindow_LabelRecordDirectoryAutoExplanation"];

        /// <summary>
        /// Choose a folder at startup
        /// </summary>
        public static string OptionsWindow_LabelRecordDirectoryChoose => JsonResourceManager.Instance["OptionsWindow_LabelRecordDirectoryChoose"];

        /// <summary>
        /// You will be prompted to select a folder each time the application starts.
        /// </summary>
        public static string OptionsWindow_LabelRecordDirectoryChooseExplanation => JsonResourceManager.Instance["OptionsWindow_LabelRecordDirectoryChooseExplanation"];

        /// <summary>
        /// Record Data Selection
        /// </summary>
        public static string OptionsWindow_LabelRecordDataSelectionGroup => JsonResourceManager.Instance["OptionsWindow_LabelRecordDataSelectionGroup"];

        /// <summary>
        /// Full data (hardware and current)
        /// </summary>
        public static string OptionsWindow_LabelRecordDataSelectionFullData => JsonResourceManager.Instance["OptionsWindow_LabelRecordDataSelectionFullData"];

        /// <summary>
        /// Hardware data
        /// </summary>
        public static string OptionsWindow_LabelRecordDataSelectionHardwareData => JsonResourceManager.Instance["OptionsWindow_LabelRecordDataSelectionHardwareData"];

        /// <summary>
        /// Unable to bind PUB socket to address
        /// </summary>
        public static string ErrorDialog_MessageBindPubSocketFailure => JsonResourceManager.Instance["ErrorDialog_MessageBindPubSocketFailure"];

        /// <summary>
        /// Unable to bind PULL socket to address
        /// </summary>
        public static string ErrorDialog_MessageBindPullSockectFailure => JsonResourceManager.Instance["ErrorDialog_MessageBindPullSockectFailure"];

        /// <summary>
        /// Unable to connect SUB socket to address
        /// </summary>
        public static string ErrorDialog_MessageConnectSubSockectFailure => JsonResourceManager.Instance["ErrorDialog_MessageConnectSubSockectFailure"];

        /// <summary>
        /// Unable to connect PUSH socket to address
        /// </summary>
        public static string ErrorDialog_MessageConnectPushSockectFailure => JsonResourceManager.Instance["ErrorDialog_MessageConnectPushSockectFailure"];

        /// <summary>
        /// Unable to transmit control message
        /// </summary>
        public static string ErrorDialog_MessageTransmitAppControlFailure => JsonResourceManager.Instance["ErrorDialog_MessageTransmitAppControlFailure"];

        /// <summary>
        /// Unable to transmit PRINT control message
        /// </summary>
        public static string ErrorDialog_MessageTransmitPrintControlFailure => JsonResourceManager.Instance["ErrorDialog_MessageTransmitPrintControlFailure"];

        /// <summary>
        /// Unable to transmit DEBUG control message
        /// </summary>
        public static string ErrorDialog_MessageTransmitDebugControlFailure => JsonResourceManager.Instance["ErrorDialog_MessageTransmitDebugControlFailure"];

        /// <summary>
        /// Unable to capture window.
        /// </summary>
        public static string ErrorDialog_MessageCaptureWindowFailure => JsonResourceManager.Instance["ErrorDialog_MessageCaptureWindowFailure"];

        /// <summary>
        /// Invalid frame header
        /// </summary>
        public static string ErrorDialog_MessageReadLogInvalidFrameHeader => JsonResourceManager.Instance["ErrorDialog_MessageReadLogInvalidFrameHeader"];

        /// <summary>
        /// Invalid hardware data header
        /// </summary>
        public static string ErrorDialog_MessageReadLogInvalidHardwareDataHeader => JsonResourceManager.Instance["ErrorDialog_MessageReadLogInvalidHardwareDataHeader"];

        /// <summary>
        /// Invalid hardware data
        /// </summary>
        public static string ErrorDialog_MessageReadLogInvalidHardwareData => JsonResourceManager.Instance["ErrorDialog_MessageReadLogInvalidHardwareData"];

        /// <summary>
        /// Invalid current value
        /// </summary>
        public static string ErrorDialog_MessageReadLogInvalidCurrentValue => JsonResourceManager.Instance["ErrorDialog_MessageReadLogInvalidCurrentValue"];

        /// <summary>
        /// Unable to open file
        /// </summary>
        public static string ErrorDialog_MessageReadLogOpenFileFailure => JsonResourceManager.Instance["ErrorDialog_MessageReadLogOpenFileFailure"];

        /// <summary>
        /// Unable to read line
        /// </summary>
        public static string ErrorDialog_MessageReadLogReadLineFailure => JsonResourceManager.Instance["ErrorDialog_MessageReadLogReadLineFailure"];

        /// <summary>
        /// Unable to open serial port
        /// </summary>
        public static string ErrorDialog_MessageSerialPortOpenPortFailure => JsonResourceManager.Instance["ErrorDialog_MessageSerialPortOpenPortFailure"];

        /// <summary>
        /// Unable to create the log folder
        /// </summary>
        public static string ErrorDialog_MessageWriteLogCreateDirectoryFailure => JsonResourceManager.Instance["ErrorDialog_MessageWriteLogCreateDirectoryFailure"];

        /// <summary>
        /// Unable to create file(s)
        /// </summary>
        public static string ErrorDialog_MessageWriteLogCreateFundamentalFileFailure => JsonResourceManager.Instance["ErrorDialog_MessageWriteLogCreateFundamentalFileFailure"];

        /// <summary>
        /// No Operation
        /// </summary>
        public static string DisplayName_HostPortUnitNop => JsonResourceManager.Instance["DisplayName_HostPortUnitNop"];

        /// <summary>
        /// Stub
        /// </summary>
        public static string DisplayName_HostPortUnitStub => JsonResourceManager.Instance["DisplayName_HostPortUnitStub"];

        /// <summary>
        /// No Operation
        /// </summary>
        public static string DisplayName_DebugPortUnitNop => JsonResourceManager.Instance["DisplayName_DebugPortUnitNop"];

        /// <summary>
        /// Stub
        /// </summary>
        public static string DisplayName_DebugPortUnitStub => JsonResourceManager.Instance["DisplayName_DebugPortUnitStub"];

        /// <summary>
        /// No Operation
        /// </summary>
        public static string DisplayName_LogPortUnitNop => JsonResourceManager.Instance["DisplayName_LogPortUnitNop"];

        /// <summary>
        /// Stub
        /// </summary>
        public static string DisplayName_LogPortUnitStub => JsonResourceManager.Instance["DisplayName_LogPortUnitStub"];

    }
}