<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <Product>JinGateway</Product>
    <AssemblyName>JinGateway</AssemblyName>
    <RootNamespace>Sony.Jin.Gateway</RootNamespace>
    <Version>0.2.0</Version>
    <BuildNumber>0</BuildNumber>
    <ReleaseYear>2026</ReleaseYear>
    <CopyrightYears>2026</CopyrightYears>
    <Month>$([MSBuild]::Add($([System.DateTime]::UtcNow.Month), $([MSBuild]::Multiply($([MSBuild]::Subtract($([System.DateTime]::UtcNow.Year), $(ReleaseYear))), 12))))</Month>
    <ClampedMonth>$([System.Math]::Min($([System.Math]::Max($(Month), 1)), 65))</ClampedMonth>
    <FileVersion>$(Version).$(ClampedMonth.PadLeft(2, '0'))$([System.DateTime]::UtcNow.Day.ToString('D2'))$(BuildNumber)</FileVersion>
    <Company>Sony Global Manufacturing &amp; Operations Corporation</Company>
    <Copyright>Copyright $(CopyrightYears) $(Company)</Copyright>
    <OutputPath>$(SolutionDir)Output\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <WarningLevel>4</WarningLevel>
    <ApplicationIcon>Assets\JIN.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="NetMQ" Version="4.0.4.3" />
    <PackageReference Include="ReactiveProperty" Version="9.9.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Reactive.Wpf" Version="7.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup Condition="'$(JinGatewayStandalone)'!='true'">
    <ProjectReference Include="..\Presentation\Presentation.csproj">
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Shared\Shared.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup Condition="'$(JinGatewayStandalone)'=='true'">
    <Reference Include="Sony.Jin.Presentation">
      <HintPath>..\External\Sony.Jin.Presentation.dll</HintPath>
    </Reference>
    <Reference Include="Sony.Jin.Shared">
      <HintPath>..\External\Sony.Jin.Shared.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\JIN.ico" />
  </ItemGroup>

  <PropertyGroup>
    <TransformOnBuild>true</TransformOnBuild>                          <!-- ビルド時にT4テンプレートを自動変換する -->
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>  <!-- 変換後にプロジェクトに含まれるファイルを最新状態にする -->
  </PropertyGroup>

  <!-- T4変換ターゲットのインポート（古いプロジェクト形式の場合） -->
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TextTemplating\Microsoft.TextTemplating.targets" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TextTemplating\Microsoft.TextTemplating.targets')" />

  <ItemGroup>
    <Compile Update="Properties\Resources.g.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.tt</DependentUpon>
    </Compile>
    <None Include="Properties\Resources.g.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.tt</DependentUpon>
    </None>
    <None Update="Properties\Resources.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Resources.g.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="resources.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <!-- サブディレクトリ dlls に .dll を集めるための処理（参照するプロジェクトについて「ローカルコピー（Private）」を False にしておく。） -->
  <Target Name="CopyDllToSubfolder" AfterTargets="AfterBuild">
    <!-- 1. メインプロジェクトの出力先（binの直下）にある NuGet 等の DLL/PDB を定義 -->
    <ItemGroup>
      <NuGetFiles Include="$(TargetDir)*.dll;$(TargetDir)*.pdb" Exclude="$(TargetDir)$(TargetName).pdb" />
    </ItemGroup>
    <!-- 2. ライブラリプロジェクトの本来の出力先にある DLL/PDB を定義 -->
    <ItemGroup>
      <MyClassLibFiles Include="$(SolutionDir).build\Shared\bin\$(Configuration)\$(TargetFramework)\*.dll" />
      <MyClassLibFiles Include="$(SolutionDir).build\Shared\bin\$(Configuration)\$(TargetFramework)\*.pdb" />
      <MyClassLibFiles Include="$(SolutionDir).build\Presentation\bin\$(Configuration)\$(TargetFramework)\*.dll" />
      <MyClassLibFiles Include="$(SolutionDir).build\Presentation\bin\$(Configuration)\$(TargetFramework)\*.pdb" />
    </ItemGroup>
    <!-- 3. サブディレクトリ（dlls）を作成 -->
    <MakeDir Directories="$(TargetDir)dlls" Condition="!Exists('$(TargetDir)dlls')" />
    <!-- 4. NuGet などの DLL を dlls に「移動」 -->
    <Move SourceFiles="@(NuGetFiles)" DestinationFolder="$(TargetDir)dlls" />
    <!-- 5. ライブラリプロジェクトの DLL を dlls に「コピー」 -->
    <Copy SourceFiles="@(MyClassLibFiles)" DestinationFolder="$(TargetDir)dlls" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CopyPyFilesToSubfolder" AfterTargets="AfterBuild">
    <ItemGroup>
      <PyFiles Include="..\PyClient\**\*.py" />
      <BatFiles Include="..\PyClient\*.bat" />
    </ItemGroup>
    <Copy SourceFiles="@(PyFiles)" DestinationFiles="@(PyFiles->'$(TargetDir)pyclient\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(BatFiles)" DestinationFiles="@(BatFiles->'$(TargetDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CleanSubfolder" AfterTargets="AfterClean">
    <ItemGroup>
      <FilesToClean Include="$(TargetDir)dlls\*" />
      <!-- 万が一 EXE の横に残ってしまった DLL もクリーン対象にする -->
      <FilesToClean Include="$(TargetDir)*.dll" Exclude="$(TargetDir)$(TargetName).dll" />
      <FilesToClean Include="$(TargetDir)*.pdb" Exclude="$(TargetDir)$(TargetName).pdb" />
      <FilesToClean Include="$(TargetDir)*.bat" />
    </ItemGroup>
    <Delete Files="@(FilesToClean)" />
    <RemoveDir Directories="$(TargetDir)dlls" Condition="Exists('$(TargetDir)dlls')" />
    <RemoveDir Directories="$(TargetDir)pyclient" Condition="Exists('$(TargetDir)pyclient')" />
  </Target>

</Project>
